"""empty message

Revision ID: 177802d96657
Revises: a113a0061570
Create Date: 2022-09-03 13:18:50.093539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177802d96657'
down_revision = 'a113a0061570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birthday_year', sa.String(length=10), nullable=True),
    sa.Column('color_eyes', sa.String(length=10), nullable=True),
    sa.Column('height', sa.String(length=5), nullable=True),
    sa.Column('mass', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('gravity', sa.String(length=10), nullable=True),
    sa.Column('terrain', sa.String(length=10), nullable=True),
    sa.Column('diametrer', sa.String(length=10), nullable=True),
    sa.Column('rotation_period', sa.String(length=10), nullable=True),
    sa.Column('orbital_period', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('people_name', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('planet_name', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['people_name'], ['people.name'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['planet_name'], ['planet.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
