"""empty message

Revision ID: 2d547c56ece2
Revises: 4d550f721cea
Create Date: 2025-01-27 19:37:13.076567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d547c56ece2'
down_revision = '4d550f721cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('opening_crawl', sa.String(), nullable=False),
    sa.Column('director', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=False),
    sa.Column('characters', sa.PickleType(), nullable=True),
    sa.Column('planets', sa.PickleType(), nullable=True),
    sa.Column('starships', sa.PickleType(), nullable=True),
    sa.Column('vehicles', sa.PickleType(), nullable=True),
    sa.Column('species', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film')
    # ### end Alembic commands ###
