"""empty message

Revision ID: 3ec0b04fe26b
Revises: f0d0125eaa95
Create Date: 2025-01-27 19:47:44.529725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ec0b04fe26b'
down_revision = 'f0d0125eaa95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_films',
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('people_id', 'film_id')
    )
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('characters')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('films')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters', postgresql.BYTEA(), autoincrement=False, nullable=True))

    op.drop_table('people_films')
    # ### end Alembic commands ###
