"""empty message

Revision ID: 42942238f3e2
Revises: daa504143f38
Create Date: 2025-01-27 20:12:41.371515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42942238f3e2'
down_revision = 'daa504143f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_starships',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'starship_id')
    )
    op.create_table('specie_films',
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['specie.id'], ),
    sa.PrimaryKeyConstraint('specie_id', 'film_id')
    )
    op.create_table('vehicle_films',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'film_id')
    )
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('species')
        batch_op.drop_column('vehicles')
        batch_op.drop_column('starships')

    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.drop_column('films')

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.drop_column('films')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('films')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starships', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicles', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('species', postgresql.BYTEA(), autoincrement=False, nullable=True))

    op.drop_table('vehicle_films')
    op.drop_table('specie_films')
    op.drop_table('film_starships')
    # ### end Alembic commands ###
