"""empty message

Revision ID: 42ef4e38db70
Revises: 5b329a8fdb57
Create Date: 2025-01-27 19:32:42.491344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ef4e38db70'
down_revision = '5b329a8fdb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(), nullable=True),
    sa.Column('starship_class', sa.String(), nullable=False),
    sa.Column('pilots', sa.PickleType(), nullable=True),
    sa.Column('films', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starship')
    # ### end Alembic commands ###
