"""empty message

Revision ID: 4d550f721cea
Revises: 6ce560d06d27
Create Date: 2025-01-27 19:35:33.230437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d550f721cea'
down_revision = '6ce560d06d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('average_height', sa.Integer(), nullable=False),
    sa.Column('skin_colors', sa.String(), nullable=False),
    sa.Column('hair_colors', sa.String(), nullable=False),
    sa.Column('eye_colors', sa.String(), nullable=True),
    sa.Column('average_lifespan', sa.Integer(), nullable=True),
    sa.Column('homeworld', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('people', sa.PickleType(), nullable=True),
    sa.Column('films', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specie')
    # ### end Alembic commands ###
