"""empty message

Revision ID: 4e58a07f97ab
Revises: 3ec0b04fe26b
Create Date: 2025-01-27 19:52:25.975176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e58a07f97ab'
down_revision = '3ec0b04fe26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'specie', ['species_id'], ['id'])
        batch_op.drop_column('species')

    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.drop_column('people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('species_id')

    # ### end Alembic commands ###
