"""empty message

Revision ID: 59b4da91942b
Revises: 58e38504e047
Create Date: 2025-01-27 21:03:36.055138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b4da91942b'
down_revision = '58e38504e047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_films',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id', 'film_id')
    )
    op.create_table('favorite_people',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id', 'people_id')
    )
    op.create_table('favorite_planets',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id', 'planet_id')
    )
    op.create_table('favorite_species',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specie_id'], ['specie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id', 'specie_id')
    )
    op.create_table('favorite_starships',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id', 'starship_id')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('resource_id')
        batch_op.drop_column('resource_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False))

    op.drop_table('favorite_starships')
    op.drop_table('favorite_species')
    op.drop_table('favorite_planets')
    op.drop_table('favorite_people')
    op.drop_table('favorite_films')
    # ### end Alembic commands ###
