"""empty message

Revision ID: 59e02ee739e9
Revises: 971841d6ee9c
Create Date: 2025-01-27 20:01:07.104529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59e02ee739e9'
down_revision = '971841d6ee9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_starships',
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('people_id', 'starship_id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('starships')

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.drop_column('pilots')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pilots', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starships', postgresql.BYTEA(), autoincrement=False, nullable=True))

    op.drop_table('people_starships')
    # ### end Alembic commands ###
