"""empty message

Revision ID: 7c4ede2f95e5
Revises: ebd9f42c5c2e
Create Date: 2024-04-14 14:39:43.357966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4ede2f95e5'
down_revision = 'ebd9f42c5c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.alter_column('favorite_character',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=125),
               existing_nullable=True)
        batch_op.drop_constraint('favorite_character_favorite_character_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['favorite_character'], ['name'])

    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.alter_column('favorite_planet',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=125),
               existing_nullable=True)
        batch_op.drop_constraint('favorite_planet_favorite_planet_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['favorite_planet'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planet_favorite_planet_fkey', 'planets', ['favorite_planet'], ['id'])
        batch_op.alter_column('favorite_planet',
               existing_type=sa.String(length=125),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_character_favorite_character_fkey', 'characters', ['favorite_character'], ['id'])
        batch_op.alter_column('favorite_character',
               existing_type=sa.String(length=125),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
