"""empty message

Revision ID: 91768e74b52b
Revises: 289b302564c3
Create Date: 2023-05-29 14:00:52.839520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91768e74b52b'
down_revision = '289b302564c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
