"""empty message

Revision ID: 971841d6ee9c
Revises: 4e58a07f97ab
Create Date: 2025-01-27 19:56:43.090786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '971841d6ee9c'
down_revision = '4e58a07f97ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_vehicles',
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('people_id', 'vehicle_id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('vehicles')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('pilots')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pilots', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles', postgresql.BYTEA(), autoincrement=False, nullable=True))

    op.drop_table('people_vehicles')
    # ### end Alembic commands ###
