"""empty message

Revision ID: a37aa409b6c0
Revises: 930f69c97f6b
Create Date: 2025-02-05 17:54:44.074728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37aa409b6c0'
down_revision = '930f69c97f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.drop_column('population')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('mass')

    # ### end Alembic commands ###
