"""empty message

Revision ID: daa504143f38
Revises: 59e02ee739e9
Create Date: 2025-01-27 20:05:07.044078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'daa504143f38'
down_revision = '59e02ee739e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_films',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('planet_id', 'film_id')
    )
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('planets')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('films')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets', postgresql.BYTEA(), autoincrement=False, nullable=True))

    op.drop_table('planet_films')
    # ### end Alembic commands ###
