"""empty message

Revision ID: ebd9f42c5c2e
Revises: 7dbdae988c98
Create Date: 2024-04-13 16:37:17.557051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd9f42c5c2e'
down_revision = '7dbdae988c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('planets_planet_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('poppulation')
        batch_op.drop_column('planet_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('poppulation', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planets_planet_name_key', ['planet_name'])
        batch_op.drop_column('population')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
